---
title: Makers Club Auckland
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title"
email: me@jonnotie.com
description: Makers Club is a monthly get together for people who enjoy making things.
baseurl: 
url: 
twitter_username: jonnotie
jonnotie: jekyll
color: "#9012FE"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
