---
title: Makers Club Auckland
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
    type: posts
  values:
    title:
    date:
    location: Golden Dawn
    at: 20:00:00 Z
    url:
    color: "#4EAAE5"
permalink: "/:categories/:title"
email: me@jonnotie.com
description: Makers Club is a monthly get together for people who enjoy making things.
baseurl:
url:
twitter_username: jonnotie
jonnotie: jekyll
color: "#4EAAE5"
event_url: https://www.facebook.com/events/1803868849875937/
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
