title: Makers Club Auckland
permalink: "/:categories/:title"
email: your-email@domain.com
description: Makers Club is a monthly get together for people who enjoy making things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Colors
color: "#9012FE"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
