---
title: Makers Club Auckland
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title"
email: your-email@domain.com
description: Makers Club is a monthly get together for people who enjoy making things.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
color: "#9012FE"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
